package com.example

import com.example.util.ExcelExportHelper
import com.example.util.ExcelReportData
import org.junit.Assert.*
import org.junit.Test
import java.io.ByteArrayInputStream
import java.util.zip.ZipInputStream

class ExcelExportTest {

    @Test
    fun testGenerateXlsxStructureAndContent() {
        val testData = ExcelReportData(
            sheetName = "Форма 8",
            title = "АКТ СПИСАНИЯ МАТОТВЕТСТВЕННОСТИ",
            subtitle = "Форма № 8 по ОКУД 6002213",
            details = listOf(
                "Подразделение" to "1-я Мотострелковая Рота",
                "Основание" to "Приказ командира № 42"
            ),
            headers = listOf("№ п/п", "Наименование", "Ед.", "Категория", "Количество", "Цена", "Сумма"),
            colWidthsChars = listOf(6.0, 30.0, 8.0, 10.0, 12.0, 12.0, 14.0),
            rows = listOf(
                listOf("1", "Бронежилет 6Б45", "шт", "1", "2", "45000", "90000"),
                listOf("2", "Шлем 6Б47", "шт", "1", "3", "28000", "84000")
            ),
            totalRow = listOf("ИТОГО ПО АКТУ:", "", "", "", "5", "", "174000"),
            signers = listOf(
                Triple("Председатель комиссии:", "Иванов И.И.", "майор"),
                Triple("Член комиссии:", "Петров П.П.", "капитан")
            )
        )

        val xlsxBytes = ExcelExportHelper.generateXlsxBytes(testData)
        assertNotNull("Generated bytes should not be null", xlsxBytes)
        assertTrue("XLSX archive must not be empty", xlsxBytes.isNotEmpty())

        // Validate ZIP packaging and required OpenXML parts
        val entryNames = mutableSetOf<String>()
        ZipInputStream(ByteArrayInputStream(xlsxBytes)).use { zis ->
            var entry = zis.nextEntry
            while (entry != null) {
                entryNames.add(entry.name)
                zis.closeEntry()
                entry = zis.nextEntry
            }
        }

        assertTrue("Must contain [Content_Types].xml", entryNames.contains("[Content_Types].xml"))
        assertTrue("Must contain _rels/.rels", entryNames.contains("_rels/.rels"))
        assertTrue("Must contain xl/workbook.xml", entryNames.contains("xl/workbook.xml"))
        assertTrue("Must contain xl/_rels/workbook.xml.rels", entryNames.contains("xl/_rels/workbook.xml.rels"))
        assertTrue("Must contain xl/styles.xml", entryNames.contains("xl/styles.xml"))
        assertTrue("Must contain xl/worksheets/sheet1.xml", entryNames.contains("xl/worksheets/sheet1.xml"))
    }
}
